### ISSUE TITLE
Feature Request: Mail body as template

### ISSUE THREAD

**Issue by bru73f0rc3** [ngoduykhanh/wireguard-ui#152] opened 2022-02-04 09:22 UTC
Hi,
Currently the Mail body is hardcoded, having this as a template would allow for easier modifications (change subject to something more custom, change body to include for example some instructions on installing wireguard, maybe to add some custom image tag...), and possibly for sending different email templates to different types of users.

**Comment by g3n35i5** [comment] 2022-02-22 08:58
Possible duplicate of #101

**Closed** 2022-02-26 12:35 UTC
