### ISSUE TITLE
Works great, just needs iptables/nat

### ISSUE THREAD

**Issue by bcookatpcsd** [ngoduykhanh/wireguard-ui#30] opened 2020-08-23 15:51 UTC
This is great, thank you so very much for this.  But I don't see the ability to add:

(example)
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

To enable forwarding clients through the wireguard server.

Am I missing something? 

There also seems to be no 'help'
```

root@art3mis ~ # ./wireguard-ui --help                                                                                                                                                                     [11:49]
Wireguard UI
App Version     : 0.2.4
Git Commit      : cd7f6e500af8f55c30c9acff7c3128880d1f2e88
Git Ref         : refs/tags/0.2.4
Build Time      : 08-23-2020 15:49:54
Git Repo        : https://github.com/ngoduykhanh/wireguard-ui
⇨ http server started on [::]:5000
^C
root@art3mis ~ # ./wireguard-ui -h                                                                                                                                                                         [11:49]
Wireguard UI
App Version     : 0.2.4
Git Commit      : cd7f6e500af8f55c30c9acff7c3128880d1f2e88
Git Ref         : refs/tags/0.2.4
Build Time      : 08-23-2020 15:49:59
Git Repo        : https://github.com/ngoduykhanh/wireguard-ui
⇨ http server started on [::]:5000
^C
root@art3mis ~ # ./wireguard-ui -?                                                                                                                                                                         [11:49]
zsh: no matches found: -?

```
Thanks in advance for anything you might be able to help me with.

**Comment by jarylc** [comment] 2020-09-07 17:32
Hey man this is a duplicate of #20. And I don't think there's arguments for the executable.

Do check my pull request out if you're using Docker, details here: https://github.com/ngoduykhanh/wireguard-ui/issues/20#issuecomment-680729935

**Comment by ngoduykhanh** [comment] 2020-09-13 20:04
Duplication. Closing...

**Closed by ngoduykhanh** 2020-09-13 20:04 UTC
